# Generated by Django 3.2.2 on 2021-07-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_likebutton_product_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likebutton',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='productlikes', to='products.product'),
        ),
        migrations.AlterField(
            model_name='likebutton',
            name='product_like',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='Like', max_length=7),
        ),
    ]
