# Generated by Django 3.2.2 on 2021-07-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_likebutton_product_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likebutton',
            name='product_like',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='Like', max_length=7),
        ),
    ]
