# Generated by Django 3.2.4 on 2021-08-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210801_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likebutton',
            name='product_like',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='Like', max_length=7),
        ),
    ]
